# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.


title: "Rachel Harris"
description: "Azure Cloud & Cybersecurity Engineer — Securing systems, driving resilience, and building for scale."
url: https://rachelanni/rachelanni.github.io"
baseurl: "rachelanni/rachelanni"
repository: "mmistakes/minimal-mistakes"
hero_title: "Rachel <span class='text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-purple-600 dark:from-indigo-400 dark:to-purple-400'>Harris</span> CV site."
hero_description: "Hello! I'm  focused web aesthetics and performance."

#remote_theme             : "mmistakes/minimal-mistakes@4.28.0"
minimal_mistakes_skin    : "neon" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Rachel Harris"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : &name "Rachel Harris" 
description              : &description "An amazing website."
url                      : "https://rachelanni.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "rachelanni/rachelanni.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"

#teaser                   : "assets/img/unsplash-gallery-image-4.jpg" # path of fallback teaser image, e.g. "/assets/images/500x300.png"
#logo                     : "assets/img/unsplash-image-11.jpg" # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
#masthead_title           : "" # overrides the website title displayed in the masthead, use " " for no title
#breadcrumbs              : "false" # true, false (default)
#words_per_minute         : "200"
#enable_copy_code_button  : "false" # true, false (default)
#copyright                : # "copyright" name, defaults to site.title
#copyright_url            : # "copyright" URL, defaults to site.url
#comments:
 # provider               :  "utterances" # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  #disqus:
    #shortname            : https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  #discourse:
    #server               : https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  #facebook:
    #https://developers.facebook.com/docs/plugins/comments
    #appid                :
    #num_posts            :  "5" # 5 (default)
    #colorscheme          :  "dark" # "light" (default), 
  #utterances:
    #theme                :  "github-dark" # "github-light" (default), 
    #issue_term           :  "pathname" # "pathname" (default)
  #giscus:
    #repo_id             : # Shown during giscus setup at https://giscus.app
    #category_name       : # Full text name of the category
    #category_id         : # Shown during giscus setup at https://giscus.app
    #discussion_term      :  "pathname" # "pathname" (default), "url", "title", "og:title"
    #reactions_enabled    :  "1'" # for enabled (default), '0' for disabled
    #theme                :  "github-dark" # "light" (default), "dark",  "transparent_dark", "preferred_color_scheme"
    #strict               :  "0" # 1 for enabled, 0 for disabled (default)
    #input_position       :  "bottom" # "top", "bottom" # The comment input box will be placed above or below the comments
    #emit_metadata        :  "0" # 1 for enabled, 0 for disabled (default) # https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#imetadatamessage
    #lang                 :  "en" # (default)
   # lazy                 :  "true" # true, false # Loading of the comments will be deferred until the user scrolls near the comments container.


# Site Settings
teaser                   : "assets/img/unsplash-image-11.jpg" # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false      #change to true to add link to talkmap on talks page
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  hide                   : false # true, false (default)
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :


# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image

# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               :  "false" #(default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    #anonymize_ip         : # true, false (default)

author:
  name      : "Rachel Harris"
  avatar    : "/assets/images/bio-photo.jpg"
  bio       : "I am a Polymath."
  email     : "rachelannie.harris@gmail.com"
  phone     : "(731) 433-9864"
  linkedin  : "rachel-harris-30468113"
  github_url: "https://rachelanni/rachelanni.github.io/"
  location  : "Memphis, TN"


# Repositories and software development
bitbucket        : # Username - Update with your username on the site
codepen          : # Username
dribbble         : # Username
github           : "rachelannie"
kaggle           : # Username  
stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    

# Social media
# bluesky        : "bsky.app" # Replace this with you Bluesky username
facebook         : # Username
flickr           : # Username
foursquare       : # Username
goodreads        : # Username
google_plus      : # Username
keybase          : # Username
instagram        : # Username
lastfm           : # Username
linkedin         : # Username
mastodon         : # URL
medium           : # URL
pinterest        : # Username
soundcloud       : # Username
steam            : # Username
telegram         : # URL
tumblr           : # Username
x                : # Username for X / Twitter
vine             : # Username
weibo            : # Username
wikipedia        : # Username
xing             : # Username
youtube          : # Username
zhihu            : # Username

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
       #url:
  since: "2011"

 # Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Dockerfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - local
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# These settings control the types of collections used by the template
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/    

# These settings control how pages and collections are included in the site
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

#Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Etc/UTC # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


#Plugins 
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-workbox-plugin
  - jekyll-turbo
  - jekyll-include-cache
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - postcss.config.js
  - vite.config.js
  - src
  - README.md
  
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-rerdirect-from
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
 #  enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    # disable this feature for development env.
    envs: [production]

# Defaults
defaults:
    # _posts
    - scope:
          path: ""
          type: posts
      values:
          layout: single
          author_profile: true
          read_time: true
          comments: true
          share: true
          related: true
          use_math: true
          toc_sticky: true

    # _pages
    - scope:
          path: ""
          type: pages
      values:
          layout: single
          author_profile: true
          read_time: false
          comments: false
          share: true
          related: false
 

 # Outputting
#defaults:
#permalink: "/posts/:path/"
#timezone: "America/New_York" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
# Pagination with jekyll-paginate
#paginate: 5 # amount of posts to show
#paginate_path: "/tabs/blog/:num"

# Pagination with jekyll-paginate-v2
# See https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
##   for configuration details
# pagination:
 # Set enabled to true to use paginate v2
 # enabled: "true"
 # debug: "false"
 # collection: 'posts'
 # per_page: 10
 # permalink: '/page/:num/'
 # title: ':title - page :num'
 # limit: 0
 # sort_field: 'date'
 # sort_reverse: "true"
 # category: 'posts'
 # tag: ''
 # locale: ''
 # trail:
 #   before: 2
 #   after: 2



#reCaptcha:
  #siteKey               :
  #secret                :


